### ISSUE TITLE
cha_aaSign / cha_auSign

### ISSUE THREAD

**Issue by Mark2Mark** [OpenInstituteCambodia/open-khmer-school#1]
Just in [Bold] the left knot is slightly differently

<img width="502" alt="screenshot 2019-02-27 at 17 10 54" src="https://user-images.githubusercontent.com/5824595/53504731-c11cf180-3ab2-11e9-8d13-976fa827bc20.png">
<img width="502" alt="screenshot 2019-02-27 at 17 10 46" src="https://user-images.githubusercontent.com/5824595/53504733-c11cf180-3ab2-11e9-9030-2fc9904af84c.png">

**Comment by sovichet** [comment]
fixed 925e292dfd9ab468fd6d7347e86d1a20c803bf89
